###################################################
#      Made by João Pedro Vicente Pansiere        #
###################################################
version: "3.1"
services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    working_dir: /application
    volumes:
      - ".:/application"
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=DB
    ports:
      - "3306:3306"
    networks:
      environment_network:
        ipv4_address: 172.30.0.2

  webserver:
    image: "nginx:alpine"
    container_name: nginx
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker.io/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      environment_network:
        ipv4_address: 172.30.0.3
    # command: sh -c "touch /var/log/nginx/application_php_errors.log && chmod 666 /var/log/nginx/application_php_errors.log && php-fpm"

  php-fpm:
    build: phpdocker.io/php-fpm
    container_name: php
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker.io/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
    networks:
      environment_network:
        ipv4_address: 172.30.0.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    networks:
      environment_network:
        ipv4_address: 172.30.0.5

networks:
  environment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
